/*
Problem title: Find the sum of all the even-valued terms in the Fibonacci sequence which do not exceed four million.

Problem description: Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

Find the sum of all the even-valued terms in the sequence which do not exceed four million.
*/

#include <stdio.h>

int main(int argc, char* argv[]) {
    int term;
    int sum = 0;

    while (term = get_fib_number()) {
        if (term > 4000000)
            break;

        if (term % 2 == 0)
            sum += term;
    }

    printf("%d\n", sum);

    return 0;
}

int get_fib_number() {
    static int term_1 = 0;
    static int term_2 = 1;
    int new_term;

    // add previous two terms to get new one
    new_term = term_1 + term_2;

    // store old terms
    term_1 = term_2;
    term_2 = new_term;

    return new_term;
}
